# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9417e23798ee5fe9b8ee279c97f4db25f2923f9b7169a93723b778fbfc3ff4b9f3a7f47f49fceb1f39965e5a91e5cd7b4eb434a3749f1d3153053983fb6bcf9b

test:
  secret_key_base: 24fede1dfcbec7f90dd2d27f43aff1301f1c97a3db86c118b57bf323fe791bb8cfc0d867789aca4b2693360d5949546a7bed77d0bb1a2222263583f2a2ee8431

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
